[setup,bugfix][s]: install additonal deps for requests if python version < 2.7.9 - fixes #94.
Doing `dpmpy publish` gives SSL errors:

```
/Users/rgrp/.virtualenvs/fd/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/Users/rgrp/.virtualenvs/fd/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
ERROR SSLError(SSLError(SSLError(1, '_ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),),)
```

Quick research shows this is a common problem and relates to having a python version < 2.7.9 (I have 2.7.8). This StackOverflow solution gives a solution:

http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package

> The docs give a fair indicator of what's required., however requests allow us to skip a few steps:
>
> You only need to install the security package extras (thanks @admdrew for pointing it out)
>
> $ pip install requests[security]
>
> or, install them directly:
>
> $ pip install pyopenssl ndg-httpsclient pyasn1

* Mod setup.py to require `requests[security]` if python version < 2.7.9.